### ISSUE TITLE
GC connection timeout - Hello

### ISSUE THREAD

**Issue by aevdokimovshs** [BeepIsla/csgo-commend-bot#340]
**Detailed bug description**
An account that has already commended the target ends up in non-working accounts.
This happens with any type of method.

**Error**
```
[Kenneth7703Smith691] Failed to login and has been marked as invalid (20/20) {
  name: 'Error',
  message: 'GC connection timeout - Hello',
  stack: 'Error: GC connection timeout - Hello\n' +
    '    at SteamUser.loggedOn (C:\\Users\\aevdokimov\\Downloads\\csgo-commend-bot-master\\csgo-commend-bot-master\\helpers\\account.js:128:14)'
```

**Config**
```
{
	"commend": {
		"friendly": 100,
		"teaching": 100,
		"leader": 100
	},
	"report": {
		"aimbot": 50,
		"wallhack": 50,
		"speedhack": 50,
		"teamharm": 0,
		"abusive": 0
	},
	"account": {
		"username": "***",
		"password": "***",
		"sharedSecret": ""
	},
	"proxy": {
		"enabled": true,
		"file": "proxies.txt",
		"switchProxyEveryXaccounts": 20
	},
	"type": "COMMEND",
	"method": "LOGIN",
	"target": "",
	"perChunk": 20,
	"betweenChunks": 300000,
	"cooldown": 28800000,
	"steamWebAPIKey": "***",
	"disableUpdateCheck": false
}

```

- NodeJS: `v12.9.1` 
- Script version: `2.7.1`

**Comment by BeepIsla** [comment]
"GC connection timeout" is unrelated to the account being already commended.

If an account is already commended the script simply doesn't select it. If it does (Which it shouldn't) then you will simply get a "Failed to send commend - Timeout" error and nothing more happens.

The account "Kenneth..." logged into Steam but failed to establish a CSGO connection. It happens when Steam/CSGO are offline (Which happens rarely). It also seems to randomly happen to some accounts, using other accounts fixes the issue for some reason. I don't know why this happens but its only specific-accounts which seem to fail.
