### ISSUE TITLE
HAPPENING WITH EVERY ACCOUNT I AM USING 

### ISSUE THREAD

**Issue by STPHITESH270** [BeepIsla/csgo-commend-bot#370]
I TRIED TO COMMEND SOME OF MY FRIENDS AND THIS ERROR POPS UP WITH EVERYONE 

THEY HAVE ZERO COMMENDS THEN HOW CAN THEY ALREADY GET COMMENDDED ?

![Screenshot_2](https://user-images.githubusercontent.com/64068560/79843005-452ce980-83d7-11ea-8e33-82c1b2a4a828.jpg)

**Comment by BeepIsla** [comment]
Stop using caps.

Ask Valve. When accounts fail to commend its a timeout, if there is a response and its code 2 that usually means "Already commended". I don't know what else it could mean.

I also recommend using a command prompt instead of a powershell due to the background of the powershell being the same as the text.

**Comment by gunther777** [comment]
This error may also occur due to the fact that you are trying to commend more than 3 profiles per day using the same accounts
