### ISSUE TITLE
Fetch target info

### ISSUE THREAD

**Issue by Borlax2** [BeepIsla/csgo-commend-bot#523]
Hi,

is it possible to fetch more info from the target beside the server and match id? for example:
adding the map name, target current score (kills +deaths) etc.. in the console
would be nice.

**Comment by BeepIsla** [comment]
Yes but why

**Comment by Borlax2** [comment]
it will look more nice & cool :)

**Comment by pelasta** [comment]
Nice idea, especially if adding the reported player's rank maybe?

**Comment by HiddenDemon** [comment]
+1, but still report bot is not working, it's always showing failure

**Comment by medhat8989** [comment]
> +1, but still report bot is not working, it's always showing failure

It's work in casual and deathmacth .in matchmaking I can reports but only when match end u have only 5or6 second to report but they're leaving so fast so that why it's hard report in live..they is why for report live but no one knows this only few people know it and they r not share with anyone because they're making money for this.
