### ISSUE TITLE
Protobuffs calls . "HOW"

### ISSUE THREAD

**Issue by kleptotic** [BeepIsla/csgo-commend-bot#607]
@BeepIsla  sorry for bothering , But i have some questions if you are willing to answer them , Im trying to make commend bot in python and i tried to follow your code but these protobuffs calls got me lost 
So to use protos in python you need to send proto call then listen back for the response
Now here is an example of me trying to create a "Fake server"
`Body = {"map":"de_dust2","server_version":13766}

cs.send(ECsgoGCMsg.EMsgGCCStrike15_v2_MatchmakingServerReservationResponse,data)
response = wait_event(ECsgoGCMsg.EMsgGCCStrike15_v2_MatchmakingServerReservationResponse,timeout = 10)
print(str(response))`
But all i get is None and i checked in game the account is not on any server
Im sure that im doing something wrong when calling in protobufs
My question is How do i know where to send the message body and from where to listen for the response 
Because i can not find anything useful or anything documentated

**Comment by BeepIsla** [comment]
> My question is How do i know where to send the message body and from where to listen for the response

You don't. You [dump](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHook2) and [analyze](https://github.com/SteamRE/SteamKit/tree/master/Resources/NetHookAnalyzer2) it yourself and replicate it.

> Because i can not find anything useful or anything documentated

Because this is Steam reverse engineering, why would this be documented.

I have never interacted with Steam using Python.

---

Don't abuse this repository for getting help.
